/**
 * G-18 / O-03 — nazwy działań z dziennika konta po ludzku. Brak wpisu = pokazujemy kod działania
 * (lepiej coś technicznego niż nic — dziennik niczego nie ukrywa).
 */
export const ETYKIETY_DZIENNIKA: Record<string, string> = {
  HOSTING_ADDON_DOMAIN_CREATED: 'Dodano domenę',
  HOSTING_ADDON_DOMAIN_DELETED: 'Usunięto domenę',
  HOSTING_AUTORESPONDER_SET: 'Ustawiono autoodpowiedź',
  HOSTING_AUTORESPONDER_DELETED: 'Usunięto autoodpowiedź',
  HOSTING_CATCHALL_SET: 'Zmieniono pocztę na nieistniejące adresy',
  HOSTING_CRON_CREATED: 'Dodano zadanie cron',
  HOSTING_CRON_DELETED: 'Usunięto zadanie cron',
  HOSTING_DB_ACCESSHOST_ADDED: 'Dodano zdalny dostęp do bazy',
  HOSTING_DB_ACCESSHOST_DELETED: 'Usunięto zdalny dostęp do bazy',
  HOSTING_DB_CREATED: 'Utworzono bazę danych',
  HOSTING_DB_DELETED: 'Usunięto bazę danych',
  HOSTING_DB_EXPORT_QUEUED: 'Zlecono eksport bazy',
  HOSTING_DB_IMPORT_QUEUED: 'Zlecono import bazy',
  HOSTING_DB_MAINTENANCE_QUEUED: 'Zlecono naprawę lub optymalizację tabel',
  HOSTING_DB_PRIVILEGES_QUEUED: 'Zmieniono uprawnienia użytkownika bazy',
  HOSTING_DB_USER_CREATED: 'Dodano użytkownika bazy',
  HOSTING_DB_USER_DELETED: 'Usunięto użytkownika bazy',
  HOSTING_DB_USER_PASSWORD_CHANGED: 'Zmieniono hasło użytkownika bazy',
  HOSTING_DIRPROTECT_SET: 'Włączono ochronę katalogu hasłem',
  HOSTING_DIRPROTECT_DELETED: 'Wyłączono ochronę katalogu hasłem',
  HOSTING_DOMAIN_PHP_SET: 'Zmieniono wersję PHP domeny',
  HOSTING_DOMAIN_POINTER_CREATED: 'Dodano alias domeny',
  HOSTING_DOMAIN_POINTER_DELETED: 'Usunięto alias domeny',
  HOSTING_EMAIL_CREATED: 'Utworzono skrzynkę e-mail',
  HOSTING_EMAIL_DELETED: 'Usunięto skrzynkę e-mail',
  HOSTING_EMAIL_FORWARD_CREATED: 'Dodano przekierowanie poczty',
  HOSTING_EMAIL_FORWARD_DELETED: 'Usunięto przekierowanie poczty',
  HOSTING_EMAIL_PASSWORD_CHANGED: 'Zmieniono hasło skrzynki e-mail',
  HOSTING_EMAIL_QUOTA_CHANGED: 'Zmieniono rozmiar skrzynki e-mail',
  HOSTING_FILE_CHMOD_SET: 'Zmieniono uprawnienia pliku',
  HOSTING_FILE_COMPRESSED: 'Spakowano pliki do archiwum',
  HOSTING_FILE_COPIED: 'Skopiowano pliki',
  HOSTING_FILE_DELETED: 'Usunięto plik',
  HOSTING_FILE_EXTRACTED: 'Rozpakowano archiwum',
  HOSTING_FILE_MOVED: 'Przeniesiono pliki',
  HOSTING_FILE_RENAMED: 'Zmieniono nazwę pliku',
  HOSTING_FILE_RESTORE_QUEUED: 'Zlecono odtworzenie pliku z kopii',
  HOSTING_FILE_UPLOADED: 'Wgrano plik',
  HOSTING_FILE_WRITTEN: 'Zapisano plik',
  HOSTING_FTP_CREATED: 'Utworzono konto FTP',
  HOSTING_FTP_DELETED: 'Usunięto konto FTP',
  HOSTING_FTP_PASSWORD_CHANGED: 'Zmieniono hasło konta FTP',
  HOSTING_GIT_CLONE_QUEUED: 'Zlecono sklonowanie repozytorium',
  HOSTING_GIT_PULL_QUEUED: 'Zlecono pobranie zmian z repozytorium',
  HOSTING_GIT_WEBHOOK_CREATED: 'Utworzono webhook wdrożenia z Gita',
  HOSTING_HTACCESS_QUEUED: 'Zmieniono ustawienia serwera WWW strony',
  HOSTING_HTACCESS_RULES_SET: 'Zmieniono reguły .htaccess',
  HOSTING_MALWARE_SCAN_QUEUED: 'Zlecono skan antywirusowy',
  HOSTING_OFFSITE_FETCH_QUEUED: 'Zlecono pobranie kopii z magazynu zewnętrznego',
  HOSTING_OFFSITE_LIST_QUEUED: 'Sprawdzono kopie w magazynie zewnętrznym',
  HOSTING_PHP_INI_SET: 'Zmieniono ustawienia PHP',
  HOSTING_QUOTA_ALERT: 'Konto zbliża się do limitu',
  HOSTING_REDIRECT_CREATED: 'Dodano przekierowanie',
  HOSTING_REDIRECT_DELETED: 'Usunięto przekierowanie',
  HOSTING_REDIS_ENABLE_QUEUED: 'Włączono Redis',
  HOSTING_REDIS_DISABLE_QUEUED: 'Wyłączono Redis',
  HOSTING_SITE_CLONE_QUEUED: 'Zlecono kopię strony na inną domenę',
  HOSTING_SPAMFILTER_SET: 'Zmieniono filtr antyspamowy',
  HOSTING_SSH_ENABLE_QUEUED: 'Włączono SSH',
  HOSTING_SSH_DISABLE_QUEUED: 'Wyłączono SSH',
  HOSTING_SSH_KEYS_QUEUED: 'Zmieniono klucze SSH',
  HOSTING_SSO_URL_CREATED: 'Otwarto phpMyAdmin lub pocztę przez przeglądarkę',
  HOSTING_SUBDOMAIN_CREATED: 'Dodano poddomenę',
  HOSTING_SUBDOMAIN_DELETED: 'Usunięto poddomenę',
  HOSTING_WP_AUTO_UPDATE_SET: 'Zmieniono automatyczne aktualizacje WordPressa',
  HOSTING_WP_CACHE_QUEUED: 'Zmieniono cache WordPressa',
  HOSTING_WP_HARDEN_QUEUED: 'Zmieniono zabezpieczenia WordPressa',
  HOSTING_WP_UPDATE_QUEUED: 'Zlecono aktualizację WordPressa',
  ASSISTANT_FIX_APPLIED: 'Asystent poprawił rekord DNS',
  ASSISTANT_FIX_UNDONE: 'Cofnięto poprawkę asystenta',
  CLIENT_WEBHOOK_CREATED: 'Dodano webhook',
  CLIENT_WEBHOOK_DELETED: 'Usunięto webhook',
  RESELLER_APPLIED: 'Złożono wniosek o program resellerski',
  RESELLER_MARKUP_CHANGED: 'Zmieniono narzut resellera',
  RESELLER_CLIENT_CREATED: 'Reseller założył konto klientowi',
  CUSTOMER_IAM_INVITE_CREATED: 'Wysłano zaproszenie',
  CUSTOMER_IAM_INVITE_ACCEPTED: 'Subkonto aktywowane',
  CUSTOMER_IAM_INVITE_REVOKED: 'Zaproszenie odwołane',
  CUSTOMER_IAM_MEMBER_UPDATED: 'Zmiana uprawnień',
  CUSTOMER_IAM_MEMBER_DISABLED: 'Subkonto wyłączone',
};
